apiVersion: v2
name: umbrella
description: Umbrella Helm chart for multiple services
type: application
version: 0.1.0

dependencies:
  - name: service-a
    version: 0.1.0
    repository: "file://../service-a"

  - name: service-b
    version: 0.1.0
    repository: "file://../service-b"
