service-a:
  replicaCount: 0
  image:
    repository: nginx
    tag: latest
  service:
    port: 80

service-b:
  replicaCount: 0
  image:
    repository: httpd
    tag: latest
  service:
    port: 80
