service-a:
  replicaCount: 1
  image:
    repository: milleniaprophet/appstore
    tag: latest
  service:
    port: 80

service-b:
  replicaCount: 1
  image:
    repository: milleniaprophet/nginx-frontend
    tag: latest
  service:
    port: 80
